name: LaTeX compilation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      uses: dante-ev/latex-action@2021-A
        with:
          root_file: unixkurs.tex
          working_directory:
          compiler:
          args:
          extra_system_packages:
          
        
