name: Build LaTeX document
on: [push, pull_request, workflow_dispatch]
jobs:
  create_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: unixkurs.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Unixkurs
          path: unixkurs.pdf
