name: Build LaTeX document
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: unixkurs.tex
      - name: Upload PDF
      - uses: actions/upload-artifact@v4
        with:
          name: Unixkurs
          path: unixkurs.pdf
